extends:
  - '@nuxtjs/eslint-config-typescript'
  - plugin:prettier/recommended
  - prettier/@typescript-eslint
rules:
  prettier/prettier:
    - error
    - singleQuote: true
      trailingComma: es5
      semi: true
  no-unused-vars: 'off'
  '@typescript-eslint/no-unused-vars':
    - warn
    - args: after-used
