extends:
  - stylelint-config-standard
  - stylelint-config-recess-order
  - stylelint-rscss/config
plugins:
  - stylelint-scss
rules:
  string-quotes: single
  no-empty-source: null
  no-duplicate-selectors: null
  selector-pseudo-class-no-unknown:
    - true
    - ignorePseudoClasses: [global]
  selector-pseudo-element-no-unknown: null
  at-rule-no-unknown: null
  scss/at-rule-no-unknown: true
  rscss/class-format:
    - true
    - component: ^[a-z0-9]+[A-Z][a-zA-Z0-9]+$
      element: ^[a-z0-9]+$
      helper: ^_[a-zA-Z0-9]+$
      variant: ^[A-Z][a-zA-Z0-9]+$
      maxDepth: 3
