root: true
env:
  browser: true
  node: true
extends:
  - standard
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - prettier
  - prettier/react
  - prettier/prettier
settings:
  react:
    version: detect
rules:
  no-use-before-define: 'off'
  react/prop-types: 'off'
overrides:
  - files:
      - '*.ts'
      - '*.tsx'
    extends:
      - plugin:@typescript-eslint/recommended
      - prettier/@typescript-eslint
