extends:
  - stylelint-config-standard
  - stylelint-config-recess-order
  - stylelint-rscss/config
rules:
  string-quotes: single
  no-empty-source: null
  rscss/class-format:
    - true
    - component: ^[a-z0-9]+[A-Z][a-zA-Z0-9]+$
      variant: ^[A-Z][a-zA-Z0-9]+$
