name: Deploy Firebase Hosting (www-preview-channel)
on:
  pull_request:
    paths:
      - workspaces/www.monalisatalk-fan.site/**.tsx
      - workspaces/www.monalisatalk-fan.site/**.ts
      - workspaces/www.monalisatalk-fan.site/**.css
      - workspaces/www.monalisatalk-fan.site/package.json
      - workspaces/www.monalisatalk-fan.site/next.config.js
      - .github/workflows/deploy-hosting-www.yml
env:
  FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
  FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
  FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
  FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
  FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
  FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
  FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
  FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}

jobs:
  deploy-functions:
    name: Deploy Firebase Hosting
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-admin-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-admin-
      - name: Install dependencies
        run: yarn ww install --frozen-lockfile
      - name: Build data resources
        run: yarn ww reflect-resources
      - name: Build Next.js app
        run: yarn ww build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          target: www
          expires: 7d
