name: Deploy Firebase Cloud Functions
on:
  push:
    branches:
      - develop
    paths:
      - workspaces/functions/**.ts
      - workspaces/functions/package.json
      - workspaces/functions/tsconfig.json
      - .github/workflows/deploy-functions.yml
env:
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
  PROJECT_ID: default

jobs:
  deploy-functions:
    name: Deploy Firebase Cloud Functions
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies
        run: yarn wf install --frozen-lockfile
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
